### ISSUE TITLE
[towhee] audio_fingerprint_beginner run raise an error"ffmpeg() got an unexpected keyword argument 'batch_size'"

### ISSUE THREAD

**Issue by jingkl** [towhee-io/examples#112]
<img width="1129" alt="截屏2022-09-27 19 57 25" src="https://user-images.githubusercontent.com/34296482/192519545-a908279c-126f-4dab-970c-89d42e715c43.png">
<img width="1209" alt="截屏2022-09-27 19 24 33" src="https://user-images.githubusercontent.com/34296482/192519588-cbfe8d7d-19fd-4351-91e7-eca2a46f367a.png">
<img width="1156" alt="截屏2022-09-27 19 24 46" src="https://user-images.githubusercontent.com/34296482/192519608-37b7f371-db30-49b5-a4ba-0cead586fc89.png">

**Comment by jaelgu** [comment]
@jingkl The audio_decode.ffmpeg operator is updated. It looks like that you have the old operator downloaded before and you need to update or re-download it:
```
rm -rf ~/.towhee/operators/audio-decode/ffmpeg
```
Remove the old cache of the operator and re-run the notebook.
