### ISSUE TITLE
[towhee] Run "video_deduplication_at_segment_level" ,raise an error"/bin/bash: tree：未找到命令"

### ISSUE THREAD

**Issue by jingkl** [towhee-io/examples#115]
**I think there needs to be a description or a way to install it**
<img width="1160" alt="截屏2022-09-28 18 36 48" src="https://user-images.githubusercontent.com/34296482/192758521-7694f1ee-4734-450d-b297-635057a2e4f8.png">

**Comment by shiyu22** [comment]
fixed with #116
