### ISSUE TITLE
 <MilvusException: (code=1, message=the data type of primary key should be int64)>

### ISSUE THREAD

**Issue by starinskycc** [towhee-io/examples#125]
![image](https://user-images.githubusercontent.com/6244330/201308537-ca82a638-2397-46e6-a978-e04ea84a8cac.png)
![image](https://user-images.githubusercontent.com/6244330/201308656-bb54bce9-4886-44d0-8c13-fb33d31107ee.png)

**Comment by shiyu22** [comment]
Hi @starinskycc, I think you need to start milvus2.1+ and reinstall the pymilvus, such as [milvu2.2.0](https://milvus.io/docs/install_standalone-docker.md) and [pymilvu2.2.0](https://milvus.io/docs/install-pymilvus.md).

**Comment by mk12306** [comment]
请问19530端口已经开放，为什么还是链接不上呢？
![image](https://user-images.githubusercontent.com/50614823/206117963-08b9256c-0a85-4dd7-a94e-ce6288393146.png)

pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on 10.25.68.126:19530. Timeout)>

**Comment by shiyu22** [comment]
@mk12306 please make sure that milvus server is started successfully, and you can try [hello milvus](https://milvus.io/docs/example_code.md) first. If there still some issue with the connectors, you can submit issue to [Milvus repo](https://github.com/milvus-io/milvus/issues).

**Comment by shiyu22** [comment]
No response for a long time, will be closed
