### ISSUE TITLE
collection.num_entities doesn't match the number of insert Data

### ISSUE THREAD

**Issue by Suhaib441** [towhee-io/examples#131]
Hello, 
Im trying to follow the tuto here https://github.com/towhee-io/examples/blob/main/image/reverse_image_search/1_build_image_search_engine.ipynb 
But when i test with 1K images and insert to milvus, the collection.num_entities gives me only 68 inserted. do you know what's wrong?

the code : 
collection = create_milvus_collection('reverse_image_search', 128)

dc = (
    towhee.glob['path']('./images/*')[:1000]
      .image_decode['path', 'img']()
      .image_embedding.timm['img', 'vec'](model_name='xcit_nano_12_p8_224')
      .ann_insert.milvus[('path', 'vec'), 'mr'](collection=collection)

)

**Comment by gokulakrishnanswaminathan** [comment]
Facing the same issue.
`
dc =  (
    towhee.glob['path']('train/*/*.JPEG').image_decode['path', 'img']().image_embedding.timm['img', 'vec'](model_name='resnet50').ann_insert.milvus[('path', 'vec'), 'mr'](collection=collection)
)
`

**Comment by shiyu22** [comment]
No response for a long time, will be closed.
