### ISSUE TITLE
dpr embedding error: TypeError: can't pickle _thread.lock objects

### ISSUE THREAD

**Issue by LemonSqi** [towhee-io/examples#185]
run demo example abnormal.
`from towhee import pipe, ops, DataCollection

if __name__ == '__main__':
    p = (
        pipe.input('text')
            .map('text', 'vec', ops.text_embedding.dpr(model_name='facebook/dpr-ctx_encoder-single-nq-base'))
            .output('text', 'vec')
    )

    DataCollection(p('Hello, world.')).show()`

Traceback (most recent call last):
  File "F:/Project/towhee_test/main.py", line 7, in <module>
    .output('text', 'vec')
  File "E:\Anaconda3\envs\towhee_env\lib\site-packages\towhee\runtime\pipeline.py", line 103, in output
    dag_dict = deepcopy(self._dag)
  File "E:\Anaconda3\envs\towhee_env\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "E:\Anaconda3\envs\towhee_env\lib\copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "E:\Anaconda3\envs\towhee_env\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "E:\Anaconda3\envs\towhee_env\lib\copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "E:\Anaconda3\envs\towhee_env\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "E:\Anaconda3\envs\towhee_env\lib\copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "E:\Anaconda3\envs\towhee_env\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "E:\Anaconda3\envs\towhee_env\lib\copy.py", line 281, in _reconstruct
    state = deepcopy(state, memo)
  File "E:\Anaconda3\envs\towhee_env\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "E:\Anaconda3\envs\towhee_env\lib\copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "E:\Anaconda3\envs\towhee_env\lib\copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread.lock objects

Process finished with exit code 1

**Comment by Shiftwa** [comment]
https://github.com/flet-dev/flet/issues/565

**Comment by Chiiizzzy** [comment]
> run demo example abnormal. `from towhee import pipe, ops, DataCollection
> 
> if **name** == '**main**': p = ( pipe.input('text') .map('text', 'vec', ops.text_embedding.dpr(model_name='facebook/dpr-ctx_encoder-single-nq-base')) .output('text', 'vec') )
> 
> ```
> DataCollection(p('Hello, world.')).show()`
> ```
> 
> Traceback (most recent call last): File "F:/Project/towhee_test/main.py", line 7, in .output('text', 'vec') File "E:\Anaconda3\envs\towhee_env\lib\site-packages\towhee\runtime\pipeline.py", line 103, in output dag_dict = deepcopy(self._dag) File "E:\Anaconda3\envs\towhee_env\lib\copy.py", line 150, in deepcopy y = copier(x, memo) File "E:\Anaconda3\envs\towhee_env\lib\copy.py", line 241, in _deepcopy_dict y[deepcopy(key, memo)] = deepcopy(value, memo) File "E:\Anaconda3\envs\towhee_env\lib\copy.py", line 150, in deepcopy y = copier(x, memo) File "E:\Anaconda3\envs\towhee_env\lib\copy.py", line 241, in _deepcopy_dict y[deepcopy(key, memo)] = deepcopy(value, memo) File "E:\Anaconda3\envs\towhee_env\lib\copy.py", line 150, in deepcopy y = copier(x, memo) File "E:\Anaconda3\envs\towhee_env\lib\copy.py", line 241, in _deepcopy_dict y[deepcopy(key, memo)] = deepcopy(value, memo) File "E:\Anaconda3\envs\towhee_env\lib\copy.py", line 180, in deepcopy y = _reconstruct(x, memo, *rv) File "E:\Anaconda3\envs\towhee_env\lib\copy.py", line 281, in _reconstruct state = deepcopy(state, memo) File "E:\Anaconda3\envs\towhee_env\lib\copy.py", line 150, in deepcopy y = copier(x, memo) File "E:\Anaconda3\envs\towhee_env\lib\copy.py", line 241, in _deepcopy_dict y[deepcopy(key, memo)] = deepcopy(value, memo) File "E:\Anaconda3\envs\towhee_env\lib\copy.py", line 169, in deepcopy rv = reductor(4) TypeError: can't pickle _thread.lock objects
> 
> Process finished with exit code 1

Are you using towhee <= 0.9?  If so, please import pipe and ops from dc2:
`from towhee.dc2 import pipe, ops, DataCollection`

**Comment by Shiftwa** [comment]
I met same as @LemonSqi, my towhee version is 0.9.0. I have tried using `from towhee.dc2 import pipe, ops, DataCollection`
, however, it's not efffective. 
When I replace` "=deepcopy(self._dag)" `with `"=self._dag"`, it works.

**Comment by LemonSqi** [comment]
this problem is solved, thanks a lot~!
