### ISSUE TITLE
在尝试执行示例代码时收到TypeError错误

### ISSUE THREAD

**Issue by mordom0404** [towhee-io/examples#187]
你好，我正在学习并尝试跟着[这个示例](https://github.com/towhee-io/examples/blob/main/image/reverse_image_search/1_build_image_search_engine.ipynb)搭建一个以图搜图的项目，我遇到了TypeError的错误。
具体是在操作到Embedding pipeline这一步时（加载图片并看到金鱼），收到了TypeError 的错误，不知道问题出在哪里，希望获得帮助，谢谢！
![QQ截图20230322184649](https://user-images.githubusercontent.com/23435286/226880626-2f79ce89-0296-4273-ac5b-34773705b854.jpg)

**Comment by shiyu22** [comment]
What's the version of towhee?

And the notebook in `main` branch needs the latest version, so can you install the latest towhee with the following code:
```python
$ git clone https://github.com/towhee-io/towhee.git
$ cd towhee
$ python setup.py install
```

**Comment by mordom0404** [comment]
我使用的是教程文档中的 `python -m pip install -q towhee>=0.9.0 pymilvus opencv-python pillow` 命令安装的towhee，pip list看到的towhee的版本是0.9.0。
我检查了VSCode中Jupyter插件版本为v2023.2.1200692131，应该是最新的版本。
我也尝试从jupyter官网安装了最新的notebook，运行的结果也是一样的TypeError错误。

随后我卸载了towhee并手动重新安装了它，现在的版本是0.9.1.Dev89，运行上面的代码时没有TypeError错误了，但还是收到了其他的错误：
`Downloading https://towhee.io/towhee/image-decode/resolve/branch/main/README.md to [C:\Users\luyao\.towhee\operators\towhee\image-decode\files](file:///C:/Users/luyao/.towhee/operators/towhee/image-decode/files): 100%|██████████| 560/560 [00:00<?, ?B/s] 
Downloading https://towhee.io/towhee/image-decode/resolve/branch/main/.gitignore to [C:\Users\luyao\.towhee\operators\towhee\image-decode\files](file:///C:/Users/luyao/.towhee/operators/towhee/image-decode/files): 100%|██████████| 3.10k/3.10k [00:00<?, ?B/s]
Downloading https://towhee.io/towhee/image-decode/resolve/branch/main/.gitattributes to [C:\Users\luyao\.towhee\operators\towhee\image-decode\files](file:///C:/Users/luyao/.towhee/operators/towhee/image-decode/files): 100%|██████████| 840/840 [00:00<00:00, 420kB/s]
Downloading https://towhee.io/towhee/image-decode/resolve/branch/main/__init__.py to [C:\Users\luyao\.towhee\operators\towhee\image-decode\files](file:///C:/Users/luyao/.towhee/operators/towhee/image-decode/files): 100%|██████████| 699/699 [00:00<00:00, 695kB/s]
Downloading https://towhee.io/towhee/image-decode/resolve/branch/main/image_decode.py to [C:\Users\luyao\.towhee\operators\towhee\image-decode\files](file:///C:/Users/luyao/.towhee/operators/towhee/image-decode/files): 100%|██████████| 329/329 [00:00<?, ?B/s] 
Downloading https://towhee.io/towhee/image-decode/resolve/branch/main/image_decode.yaml to [C:\Users\luyao\.towhee\operators\towhee\image-decode\files](file:///C:/Users/luyao/.towhee/operators/towhee/image-decode/files): 100%|██████████| 241/241 [00:00<00:00, 243kB/s]
Downloading https://towhee.io/towhee/image-decode/resolve/branch/main/requirements.txt to [C:\Users\luyao\.towhee\operators\towhee\image-decode\files](file:///C:/Users/luyao/.towhee/operators/towhee/image-decode/files): 100%|██████████| 20.0/20.0 [00:00<00:00, 20.0kB/s]
2023-03-23 10:44:49,354 - 31944 - operator_loader.py-operator_loader:128 - ERROR: [WinError 183] 当文件已存在时，无法创建该文件。: '[C:\\Users\\luyao\\.towhee\\operators\\towhee\\image-decode\\tmptwk29dhd](file:///C://Users//luyao//.towhee//operators//towhee//image-decode//tmptwk29dhd)' -> '[C:\\Users\\luyao\\.towhee\\operators\\towhee\\image-decode\\versions\\main](file:///C://Users//luyao//.towhee//operators//towhee//image-decode//versions//main)', Traceback (most recent call last):
  File "[c:\Users\luyao\AppData\Local\Programs\Python\Python310\lib\site-packages\towhee-0.9.1.dev89-py3.10.egg\towhee\runtime\operator_manager\operator_loader.py](file:///C:/Users/luyao/AppData/Local/Programs/Python/Python310/lib/site-packages/towhee-0.9.1.dev89-py3.10.egg/towhee/runtime/operator_manager/operator_loader.py)", line 125, in _load_operator_from_hub
    path = get_operator(operator=function, tag=tag, latest=latest)
  File "[c:\Users\luyao\AppData\Local\Programs\Python\Python310\lib\site-packages\towhee-0.9.1.dev89-py3.10.egg\towhee\hub\__init__.py](file:///C:/Users/luyao/AppData/Local/Programs/Python/Python310/lib/site-packages/towhee-0.9.1.dev89-py3.10.egg/towhee/hub/__init__.py)", line 23, in get_operator
    return _CACHE_MANAGER.get_operator(operator, tag, install_reqs, latest)
  File "[c:\Users\luyao\AppData\Local\Programs\Python\Python310\lib\site-packages\towhee-0.9.1.dev89-py3.10.egg\towhee\hub\cache_manager.py](file:///C:/Users/luyao/AppData/Local/Programs/Python/Python310/lib/site-packages/towhee-0.9.1.dev89-py3.10.egg/towhee/hub/cache_manager.py)", line 89, in get_operator
    download_operator(author, repo, tag, download_path, install_reqs, latest)
  File "[c:\Users\luyao\AppData\Local\Programs\Python\Python310\lib\site-packages\towhee-0.9.1.dev89-py3.10.egg\towhee\hub\downloader.py](file:///C:/Users/luyao/AppData/Local/Programs/Python/Python310/lib/site-packages/towhee-0.9.1.dev89-py3.10.egg/towhee/hub/downloader.py)", line 174, in download_operator
    fs.symlink_files(latest)
  File "[c:\Users\luyao\AppData\Local\Programs\Python\Python310\lib\site-packages\towhee-0.9.1.dev89-py3.10.egg\towhee\hub\downloader.py](file:///C:/Users/luyao/AppData/Local/Programs/Python/Python310/lib/site-packages/towhee-0.9.1.dev89-py3.10.egg/towhee/hub/downloader.py)", line 104, in symlink_files
    tmp_dir.rename(self.get_tag_path(True))
  File "[c:\Users\luyao\AppData\Local\Programs\Python\Python310\lib\pathlib.py](file:///C:/Users/luyao/AppData/Local/Programs/Python/Python310/lib/pathlib.py)", line 1232, in rename
    self._accessor.rename(self, target)
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: '[C:\\Users\\luyao\\.towhee\\operators\\towhee\\image-decode\\tmptwk29dhd](file:///C://Users//luyao//.towhee//operators//towhee//image-decode//tmptwk29dhd)' -> '[C:\\Users\\luyao\\.towhee\\operators\\towhee\\image-decode\\versions\\main](file:///C://Users//luyao//.towhee//operators//towhee//image-decode//versions//main)'`

我尝试清除了C:\Users\luyao\.towhee\operators\towhee下的所有文件后依然如此。

**Comment by shiyu22** [comment]
How about removing this folder: `C://Users//luyao//.towhee//operators//towhee//image-decode/`

**Comment by mordom0404** [comment]
> How about removing this folder: `C://Users//luyao//.towhee//operators//towhee//image-decode/`

试过了，程序会重新创建这个文件夹，但是然后收到同样错误。

**Comment by shiyu22** [comment]
> > How about removing this folder: `C://Users//luyao//.towhee//operators//towhee//image-decode/`
> 
> 试过了，程序会重新创建这个文件夹，但是然后收到同样错误。

Actually it works in my env, and can you run image-decode with ops:
```python
op = ops.image_decode()
path = 'your-image-path'
op(path)
```

**Comment by mordom0404** [comment]
> > > How about removing this folder: `C://Users//luyao//.towhee//operators//towhee//image-decode/`
> > 
> > 
> > 试过了，程序会重新创建这个文件夹，但是然后收到同样错误。
> 
> Actually it works in my env, and can you run image-decode with `ops`:
> 
> ```python
> from towhee import ops
> op1 = ops.image_decode()
> path = 'your-image-path'
> op1(path)
> ```

```python
from towhee import ops
op1 = ops.image_decode()
path = './test/Afghan_hound/n02088094_4261.JPEG'
op1(path)
```
一开始我收到了同样的错误，然后我尝试重装了towhee（不知道为什么现在安装又变成0.9.0了）然后还重启了notebook，现在这段代码可以成功执行。

>
```
Cloning the repo: towhee/image-decode... Be patient and waiting printing 'Successfully'.
Successfully clone the repo: towhee/image-decode.
Cloning the repo: image-decode/cv2... Be patient and waiting printing 'Successfully'.
Successfully clone the repo: image-decode/cv2.
Image([[[174, 191, 194],
        [176, 192, 198],
        [182, 198, 204],
        ...,
```

**Comment by shiyu22** [comment]
Oh, you need to uninstall with `pip uninstall towhee` and reinstall it. So it works now, right?

**Comment by mordom0404** [comment]
> Oh, you need to uninstall with `pip uninstall towhee` and reinstall it. So it works now, right?

不，刚才只是上面这段尝试decode一张测试图片的代码能够正常执行，但教程文档中摘录下来的的这些代码和一开始一样仍然无法执行（TypeError错误）
``` python
import csv
from glob import glob
from pathlib import Path
from statistics import mean

from towhee import pipe, ops, DataCollection
from pymilvus import connections, FieldSchema, CollectionSchema, DataType, Collection, utility


# Towhee parameters
MODEL = 'resnet50'
DEVICE = None # if None, use default device (cuda is enabled if available)

# Milvus parameters
HOST = '127.0.0.1'
PORT = '19530'
TOPK = 10
DIM = 2048 # dimension of embedding extracted by MODEL
COLLECTION_NAME = 'reverse_image_search'
INDEX_TYPE = 'IVF_FLAT'
METRIC_TYPE = 'L2'

# path to csv (column_1 indicates image path) OR a pattern of image paths
INSERT_SRC = 'reverse_image_search.csv'
QUERY_SRC = './test/*/*.JPEG'

# Load image path
def load_image(x):
    if x.endswith('csv'):
        with open(x) as f:
            reader = csv.reader(f)
            next(reader)
            for item in reader:
                yield item[1]
    else:
        for item in glob(x):
            yield item
            
# Embedding pipeline
p_embed = (
    pipe.input('src')
        .flat_map('src', 'img_path', load_image)
        .map('img_path', 'img', ops.image_decode())
        .map('img', 'vec', ops.image_embedding.timm(model_name=MODEL, device=DEVICE))
)

# Display embedding result, no need for implementation
p_display = p_embed.output('img_path', 'img', 'vec')
DataCollection(p_display('./test/goldfish/*.JPEG')).show()
```

> 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 44
     37             yield item
     39 # Embedding pipeline
     40 p_embed = (
     41     pipe.input('src')
     42         .flat_map('src', 'img_path', load_image)
     43         .map('img_path', 'img', ops.image_decode())
---> 44         .map('img', 'vec', ops.image_embedding.timm(model_name=MODEL, device=DEVICE))
     45 )
     47 # Display embedding result, no need for implementation
     48 p_display = p_embed.output('img_path', 'img', 'vec')

File [c:\Users\luyao\AppData\Local\Programs\Python\Python310\lib\site-packages\towhee\runtime\pipeline.py:143](file:///C:/Users/luyao/AppData/Local/Programs/Python/Python310/lib/site-packages/towhee/runtime/pipeline.py:143), in Pipeline.map(self, input_schema, output_schema, fn, config)
    141 uid = uuid.uuid4().hex
    142 fn_action = self._to_action(fn)
--> 143 dag_dict = deepcopy(self._dag)
    144 dag_dict[uid] = {
    145     'inputs': input_schema,
    146     'outputs': output_schema,
   (...)
    153     'next_nodes': [],
    154 }
    155 dag_dict[self._clo_node]['next_nodes'].append(uid)
...省略
```

**Comment by shiyu22** [comment]
@mordom0404 Got it, can you show the whole error message(file is ok)? I cannot reproduce it with Linux.

**Comment by mordom0404** [comment]
> @mordom0404 Got it, can you show the whole error message(file is ok)? I cannot reproduce it with Linux.

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 44
     37             yield item
     39 # Embedding pipeline
     40 p_embed = (
     41     pipe.input('src')
     42         .flat_map('src', 'img_path', load_image)
     43         .map('img_path', 'img', ops.image_decode())
---> 44         .map('img', 'vec', ops.image_embedding.timm(model_name=MODEL, device=DEVICE))
     45 )
     47 # Display embedding result, no need for implementation
     48 p_display = p_embed.output('img_path', 'img', 'vec')

File [c:\Users\luyao\AppData\Local\Programs\Python\Python310\lib\site-packages\towhee\runtime\pipeline.py:143](file:///C:/Users/luyao/AppData/Local/Programs/Python/Python310/lib/site-packages/towhee/runtime/pipeline.py:143), in Pipeline.map(self, input_schema, output_schema, fn, config)
    141 uid = uuid.uuid4().hex
    142 fn_action = self._to_action(fn)
--> 143 dag_dict = deepcopy(self._dag)
    144 dag_dict[uid] = {
    145     'inputs': input_schema,
    146     'outputs': output_schema,
   (...)
    153     'next_nodes': [],
    154 }
    155 dag_dict[self._clo_node]['next_nodes'].append(uid)

File [c:\Users\luyao\AppData\Local\Programs\Python\Python310\lib\copy.py:146](file:///C:/Users/luyao/AppData/Local/Programs/Python/Python310/lib/copy.py:146), in deepcopy(x, memo, _nil)
    144 copier = _deepcopy_dispatch.get(cls)
    145 if copier is not None:
--> 146     y = copier(x, memo)
    147 else:
    148     if issubclass(cls, type):

File [c:\Users\luyao\AppData\Local\Programs\Python\Python310\lib\copy.py:231](file:///C:/Users/luyao/AppData/Local/Programs/Python/Python310/lib/copy.py:231), in _deepcopy_dict(x, memo, deepcopy)
    229 memo[id(x)] = y
    230 for key, value in x.items():
--> 231     y[deepcopy(key, memo)] = deepcopy(value, memo)
    232 return y

File [c:\Users\luyao\AppData\Local\Programs\Python\Python310\lib\copy.py:146](file:///C:/Users/luyao/AppData/Local/Programs/Python/Python310/lib/copy.py:146), in deepcopy(x, memo, _nil)
    144 copier = _deepcopy_dispatch.get(cls)
    145 if copier is not None:
--> 146     y = copier(x, memo)
    147 else:
    148     if issubclass(cls, type):

File [c:\Users\luyao\AppData\Local\Programs\Python\Python310\lib\copy.py:231](file:///C:/Users/luyao/AppData/Local/Programs/Python/Python310/lib/copy.py:231), in _deepcopy_dict(x, memo, deepcopy)
    229 memo[id(x)] = y
    230 for key, value in x.items():
--> 231     y[deepcopy(key, memo)] = deepcopy(value, memo)
    232 return y

File [c:\Users\luyao\AppData\Local\Programs\Python\Python310\lib\copy.py:146](file:///C:/Users/luyao/AppData/Local/Programs/Python/Python310/lib/copy.py:146), in deepcopy(x, memo, _nil)
    144 copier = _deepcopy_dispatch.get(cls)
    145 if copier is not None:
--> 146     y = copier(x, memo)
    147 else:
    148     if issubclass(cls, type):

File [c:\Users\luyao\AppData\Local\Programs\Python\Python310\lib\copy.py:231](file:///C:/Users/luyao/AppData/Local/Programs/Python/Python310/lib/copy.py:231), in _deepcopy_dict(x, memo, deepcopy)
    229 memo[id(x)] = y
    230 for key, value in x.items():
--> 231     y[deepcopy(key, memo)] = deepcopy(value, memo)
    232 return y

File [c:\Users\luyao\AppData\Local\Programs\Python\Python310\lib\copy.py:172](file:///C:/Users/luyao/AppData/Local/Programs/Python/Python310/lib/copy.py:172), in deepcopy(x, memo, _nil)
    170                 y = x
    171             else:
--> 172                 y = _reconstruct(x, memo, *rv)
    174 # If is its own copy, don't memoize.
    175 if y is not x:

File [c:\Users\luyao\AppData\Local\Programs\Python\Python310\lib\copy.py:271](file:///C:/Users/luyao/AppData/Local/Programs/Python/Python310/lib/copy.py:271), in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    269 if state is not None:
    270     if deep:
--> 271         state = deepcopy(state, memo)
    272     if hasattr(y, '__setstate__'):
    273         y.__setstate__(state)

File [c:\Users\luyao\AppData\Local\Programs\Python\Python310\lib\copy.py:146](file:///C:/Users/luyao/AppData/Local/Programs/Python/Python310/lib/copy.py:146), in deepcopy(x, memo, _nil)
    144 copier = _deepcopy_dispatch.get(cls)
    145 if copier is not None:
--> 146     y = copier(x, memo)
    147 else:
    148     if issubclass(cls, type):

File [c:\Users\luyao\AppData\Local\Programs\Python\Python310\lib\copy.py:231](file:///C:/Users/luyao/AppData/Local/Programs/Python/Python310/lib/copy.py:231), in _deepcopy_dict(x, memo, deepcopy)
    229 memo[id(x)] = y
    230 for key, value in x.items():
--> 231     y[deepcopy(key, memo)] = deepcopy(value, memo)
    232 return y

File [c:\Users\luyao\AppData\Local\Programs\Python\Python310\lib\copy.py:161](file:///C:/Users/luyao/AppData/Local/Programs/Python/Python310/lib/copy.py:161), in deepcopy(x, memo, _nil)
    159 reductor = getattr(x, "__reduce_ex__", None)
    160 if reductor is not None:
--> 161     rv = reductor(4)
    162 else:
    163     reductor = getattr(x, "__reduce__", None)

TypeError: cannot pickle '_thread.lock' object
```

**Comment by Chiiizzzy** [comment]
> 

try import pipe and ops from dc2 instead of dc

**Comment by shiyu22** [comment]
@mordom0404 This error occurs in towhee0.9, so please check the version.

If you are using towhee0.9, you can run with `from towhee.dc2 import pipe, ops`, and refer to this issue #185.

**Comment by mordom0404** [comment]
> @mordom0404 This error occurs in towhee0.9, so please check the version.
> 
> If you are using towhee0.9, you can run with `from towhee.dc2 import pipe, ops`, and refer to this issue #185.

看起来问题解决了，感谢你的耐心回复~
