### ISSUE TITLE
towhee pipe error

### ISSUE THREAD

**Issue by bhuvneshsaini** [towhee-io/examples#189]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[5], line 15
     11             yield item
     13 # Embedding pipeline
     14 p_embed = (
---> 15     pipe.input('src')
     16         .flat_map('src', 'img_path', load_image)
     17         .map('img_path', 'img', ops.image_decode())
     18         .map('img', 'vec', ops.image_embedding.timm(model_name=MODEL, device=DEVICE))
     19 )

File ~/Desktop/Projects/vector_database/milvus/venv/lib/python3.8/site-packages/towhee/runtime/pipeline.py:143, in Pipeline.map(self, input_schema, output_schema, fn, config)
    141 uid = uuid.uuid4().hex
    142 fn_action = self._to_action(fn)
--> 143 dag_dict = deepcopy(self._dag)
    144 dag_dict[uid] = {
    145     'inputs': input_schema,
    146     'outputs': output_schema,
   (...)
    153     'next_nodes': [],
    154 }
    155 dag_dict[self._clo_node]['next_nodes'].append(uid)

File /usr/lib/python3.8/copy.py:146, in deepcopy(x, memo, _nil)
    144 copier = _deepcopy_dispatch.get(cls)
    145 if copier is not None:
--> 146     y = copier(x, memo)
    147 else:
    148     if issubclass(cls, type):

File /usr/lib/python3.8/copy.py:230, in _deepcopy_dict(x, memo, deepcopy)
    228 memo[id(x)] = y
    229 for key, value in x.items():
--> 230     y[deepcopy(key, memo)] = deepcopy(value, memo)
    231 return y

File /usr/lib/python3.8/copy.py:146, in deepcopy(x, memo, _nil)
    144 copier = _deepcopy_dispatch.get(cls)
    145 if copier is not None:
--> 146     y = copier(x, memo)
    147 else:
    148     if issubclass(cls, type):

File /usr/lib/python3.8/copy.py:230, in _deepcopy_dict(x, memo, deepcopy)
    228 memo[id(x)] = y
    229 for key, value in x.items():
--> 230     y[deepcopy(key, memo)] = deepcopy(value, memo)
    231 return y

File /usr/lib/python3.8/copy.py:146, in deepcopy(x, memo, _nil)
    144 copier = _deepcopy_dispatch.get(cls)
    145 if copier is not None:
--> 146     y = copier(x, memo)
    147 else:
    148     if issubclass(cls, type):

File /usr/lib/python3.8/copy.py:230, in _deepcopy_dict(x, memo, deepcopy)
    228 memo[id(x)] = y
    229 for key, value in x.items():
--> 230     y[deepcopy(key, memo)] = deepcopy(value, memo)
    231 return y

File /usr/lib/python3.8/copy.py:172, in deepcopy(x, memo, _nil)
    170                 y = x
    171             else:
--> 172                 y = _reconstruct(x, memo, *rv)
    174 # If is its own copy, don't memoize.
    175 if y is not x:

File /usr/lib/python3.8/copy.py:270, in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    268 if state is not None:
    269     if deep:
--> 270         state = deepcopy(state, memo)
    271     if hasattr(y, '__setstate__'):
    272         y.__setstate__(state)

File /usr/lib/python3.8/copy.py:146, in deepcopy(x, memo, _nil)
    144 copier = _deepcopy_dispatch.get(cls)
    145 if copier is not None:
--> 146     y = copier(x, memo)
    147 else:
    148     if issubclass(cls, type):

File /usr/lib/python3.8/copy.py:230, in _deepcopy_dict(x, memo, deepcopy)
    228 memo[id(x)] = y
    229 for key, value in x.items():
--> 230     y[deepcopy(key, memo)] = deepcopy(value, memo)
    231 return y

File /usr/lib/python3.8/copy.py:161, in deepcopy(x, memo, _nil)
    159 reductor = getattr(x, "__reduce_ex__", None)
    160 if reductor is not None:
--> 161     rv = reductor(4)
    162 else:
    163     reductor = getattr(x, "__reduce__", None)

TypeError: cannot pickle '_thread.lock' object

**Comment by bhuvneshsaini** [comment]
I am running the jupyter notebook provided by Milvus, but getting the error above

**Comment by tansangxtt** [comment]
> 

Me too, but use "milvus2.0" branch is fine

```
%%time
import os
import towhee

device = 'cuda:0'
# device = 'cpu'

# For the first time you run this line, 
# it will take some time 
# because towhee will download operator with weights on backend.
dc = (
    towhee.read_csv(test_sample_csv_path).unstream()
      .runas_op['video_id', 'id'](func=lambda x: int(x[-4:]))
      .video_decode.ffmpeg['video_path', 'frames'](sample_type='uniform_temporal_subsample', args={'num_samples': 12}) \
      .runas_op['frames', 'frames'](func=lambda x: [y for y in x]) \
      .video_text_embedding.clip4clip['frames', 'vec'](model_name='clip_vit_b32', modality='video', device=device) \
      .to_milvus['id', 'vec'](collection=collection, batch=30)
)
```

**Comment by shiyu22** [comment]
Please check with [this issue](https://github.com/towhee-io/examples/issues/185), it is cause by that we haven't publish the latest towhee, and the `main` code is for the latest. And I will back to the code for 0.9.0.

**Comment by jawhster** [comment]
Thank you for this example and thanks for back to 0.9.0 from towhee to towhee.dc2. When do you think may publish latest towhee from main? Unfortunately, even after back to 0.9.0 code, I am still getting below error on step 3: train model with `clip_op.train(data_args=data_args, training_args=training_args, model_args=model_args`

ImportError: cannot import name 'get_dataclasses_help' from 'towhee.trainer.training_config' (/opt/conda/lib/python3.9/site-packages/towhee/trainer/training_config.py)

**Comment by zc277584121** [comment]
@jawhster It is cause by that we haven't publish the latest towhee, and we will release the latest version of towhee soon. You can use the towhee newest main branch or branch1.0 to solve it temporarily.

**Comment by jaelgu** [comment]
Reopen if the issue persists in the latest version.
