### ISSUE TITLE
[Text Image Search] RuntimeError: Node-ann-insert/milvus-client-4 runs failed

### ISSUE THREAD

**Issue by LiuersNick** [towhee-io/examples#192]
Hi there,
When I clone and tried to run the project "text_image_search"(branch is main), an error occurred during the step "Load Image Embeddings into Milvus". The error is shown in the screenshot below:
![image](https://user-images.githubusercontent.com/59303811/233359125-6c8f72ff-ce17-4aa3-83d3-d9307f9c804f.png)
p.s. I am using milvus 2.0.2, and pymilvus is 2.0.2. Also using towhee 0.9.0.
(please forgive my poor english :)

**Comment by junjiejiangjjj** [comment]
The operator used the interface of pymilvus 2.2.0. I will modify it so that the operator can also run on pymilvus 2.0.2.

**Comment by junjiejiangjjj** [comment]
Please remove the op cache: ~/.towhee/operators/ann-insert/milvus-client/ and rerun your code

**Comment by LiuersNick** [comment]
> Please remove the op cache: ~/.towhee/operators/ann-insert/milvus-client/ and rerun your code

Thanks for your reply. Did you mean I need to delete this folder ```~/.towhee/operators/ann-insert/milvus-client/``` and rerun my code?

**Comment by junjiejiangjjj** [comment]
> > Please remove the op cache: ~/.towhee/operators/ann-insert/milvus-client/ and rerun your code
> 
> Thanks for your reply. Did you mean I need to delete this folder `~/.towhee/operators/ann-insert/milvus-client/` and rerun my code?

yeah

> 
> > The operator used the interface of pymilvus 2.2.0. I will modify it so that the operator can also run on pymilvus 2.0.2.
> 
> It means I can upgrade the milvus and pymilvus to 2.2.0 to solve the problems?

I am not sure if using pymilvus2.2.0 to access milvus2.0.2 will work properly.

**Comment by LiuersNick** [comment]
> > > Please remove the op cache: ~/.towhee/operators/ann-insert/milvus-client/ and rerun your code
> > 
> > 
> > Thanks for your reply. Did you mean I need to delete this folder `~/.towhee/operators/ann-insert/milvus-client/` and rerun my code?
> 
> yeah
> 
> > > The operator used the interface of pymilvus 2.2.0. I will modify it so that the operator can also run on pymilvus 2.0.2.
> > 
> > 
> > It means I can upgrade the milvus and pymilvus to 2.2.0 to solve the problems?
> 
> I am not sure if using pymilvus2.2.0 to access milvus2.0.2 will work properly.

I deleted the folder ```~/.towhee/operators/ann-insert/milvus-client/``` and it works! 

Thanks again for your reply, and it helps me a lot!
