### ISSUE TITLE
[Text Image Search] AttributeError: 'DataQueue' object has no attribute 'to_list'

### ISSUE THREAD

**Issue by LiuersNick** [towhee-io/examples#193]
Hi there :-）
> Using milvus 2.0.2, and pymilvus is 2.0.2. Also using towhee 0.9.0 , pandas 2.0.1 and numpy 1.24.3

I got a new problem when I was running the program "Text Image Search" from examples. While running the step "Release a Showcase", an error occurred like:
```
Traceback (most recent call last):
  File "/home/liu/anaconda3/envs/py39/lib/python3.9/site-packages/gradio/routes.py", line 401, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/liu/anaconda3/envs/py39/lib/python3.9/site-packages/gradio/blocks.py", line 1302, in process_api
    result = await self.call_function(
  File "/home/liu/anaconda3/envs/py39/lib/python3.9/site-packages/gradio/blocks.py", line 1025, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/liu/anaconda3/envs/py39/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/liu/anaconda3/envs/py39/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/liu/anaconda3/envs/py39/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/tmp/ipykernel_606/2799569186.py", line 14, in search
    image_ids = search_pipeline(text).to_list()[0][0]
AttributeError: 'DataQueue' object has no attribute 'to_list'
```
And the code "Release a Showcase" is below:
```python
search_pipeline = (
    pipe.input('text')
    .map('text', 'vec', ops.image_text_embedding.clip(model_name='clip_vit_base_patch16', modality='text'))
    .map('vec', 'vec', lambda x: x / np.linalg.norm(x))
    .map('vec', 'result', ops.ann_search.milvus_client(host='127.0.0.1', port='19530', collection_name='text_image_search', limit=5))
    .map('result', 'image_ids', lambda x: [item[0] for item in x])
    .output('image_ids')
)

def search(text):
    df = pd.read_csv('reverse_image_search.csv')
    id_img = df.set_index('id')['path'].to_dict()
    imgs = []
    image_ids = search_pipeline(text).to_list()[0][0]
    return [id_img[image_id] for image_id in image_ids]

import gradio

interface = gradio.Interface(search, 
                             gradio.inputs.Textbox(lines=1),
                             [gradio.outputs.Image(type="filepath", label=None) for _ in range(5)]
                            )

interface.launch(inline=True, share=True)
```
> P.s. I once deleted the folder ***"~/.towhee/operator/ann-insert/milvus-client/"*** before because of #192 , and I don't know if this has any impact on this issue？

**Comment by LiuersNick** [comment]
And I found that DataQueue has method "to_list" in the doc :
![image](https://user-images.githubusercontent.com/59303811/234474287-fdc72f39-1e5a-4344-aa20-2164dc491406.png)

**Comment by LiuersNick** [comment]
But I also found that I cannot find the method "to_list" in the data_queue.py from my conda env like ***"\home\liu\anaconda3\envs\TIS\lib\python3.9\site-packages\towhee\runtime\data_queue.py"***, which has listed in doc ?
![image](https://user-images.githubusercontent.com/59303811/234479131-642fdd81-2992-493f-b494-b78f22f2f1b0.png)
![image](https://user-images.githubusercontent.com/59303811/234479266-9d9d612f-806f-4aee-a11c-291efdd6c100.png)
> I am sure that I am using towhee 0.9.0 and I used pip3 to install it before.
Thanks a lot !

**Comment by junjiejiangjjj** [comment]
Sorry, `to_list` is a new interface in version 1.0,   0.9.0 only support `data_queue.get()` or `data_queue.get_dict()`

```python
ret = [data_queue.get() for _ in range(data_queue.size)]
```

**Comment by LiuersNick** [comment]
> Sorry, `to_list` is a new interface in version 1.0, 0.9.0 only support `data_queue.get()` or `data_queue.get_dict()`
> 
> ```python
> ret = [data_queue.get() for _ in range(data_queue.size)]
> ```

Thanks for your tips and i will try to using ```to_dict()``` additionally :-)
