### ISSUE TITLE
TypeError: cannot pickle '_thread.lock' object

### ISSUE THREAD

**Issue by mastreips** [towhee-io/examples#198]
I get the following error when running the Embedding Pipeline in the 1_build_image_search_engine.ipynb notebook

TypeError: cannot pickle '_thread.lock' object

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 18
     11             yield item
     13 # Embedding pipeline
     14 p_embed = (
     15     pipe.input('src')
     16         .flat_map('src', 'img_path', load_image)
     17         .map('img_path', 'img', ops.image_decode())
---> 18         .map('img', 'vec', ops.image_embedding.timm(model_name=MODEL, device=DEVICE))
     19 )

File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/towhee/runtime/pipeline.py:143, in Pipeline.map(self, input_schema, output_schema, fn, config)
    141 uid = uuid.uuid4().hex
    142 fn_action = self._to_action(fn)
--> 143 dag_dict = deepcopy(self._dag)
    144 dag_dict[uid] = {
    145     'inputs': input_schema,
    146     'outputs': output_schema,
   (...)
    153     'next_nodes': [],
    154 }
    155 dag_dict[self._clo_node]['next_nodes'].append(uid)

File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/copy.py:146, in deepcopy(x, memo, _nil)
...
--> 161     rv = reductor(4)
    162 else:
    163     reductor = getattr(x, "__reduce__", None)

TypeError: cannot pickle '_thread.lock' object

**Comment by junjiejiangjjj** [comment]
The examples require towhee 1.0.0rc1, which can be installed with pip install towhee==1.0.0rc1

**Comment by jaelgu** [comment]
Reopen if the issue persists in the latest version.
