### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by JN0925** [towhee-io/examples#199]
Node-image-text-embedding/clip-2 runs failed, error msg: Create image-text-embedding/clip-2 operator image-text-embedding/clip:main with args None and kws {'model_name': 'clip_vit_base_patch16', 'modality': 'image', 'device': 0} failed, err: Torch not compiled with CUDA enabled, Traceback (most recent call last): File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/towhee-0.9.1.dev111-py3.9.egg/towhee/runtime/nodes/node.py", line 88

in initialize, system: macOS Big Sur ，cuda: Intel Iris 1536 MB

**Comment by junjiejiangjjj** [comment]
https://developer.apple.com/metal/pytorch/ Make sure your system supports GPU.
if supports, set the device to 'mps': `ops.image_text_embedding.clip(model_name='clip_vit_base_patch16', modality='image', device='mps')`, if not  do set set device: `ops.image_text_embedding.clip(model_name='clip_vit_base_patch16', modality='image')`

**Comment by JN0925** [comment]
修改为ops.image_text_embedding.clip(model_name='clip_vit_base_patch16', modality='image')后，报了另外的一个错误。AttributeError                            Traceback (most recent call last)
File :23

AttributeError: 'RuntimePipeline' object has no attribute 'profiler'。  
<img width="915" alt="image" src="https://github.com/towhee-io/examples/assets/16714959/45215a5c-3314-46fd-b789-56874cfe2d63">

**Comment by junjiejiangjjj** [comment]
Which version of Towhee are you using? This interface only exists in versions 0.9 and 1.0, and has been deleted in the main branch.

**Comment by JN0925** [comment]
towhee版本是0.9.1.dev111。
<img width="785" alt="image" src="https://github.com/towhee-io/examples/assets/16714959/ce50f0c3-25bd-40e9-9c7a-39326ac3c960">

**Comment by junjiejiangjjj** [comment]
try towhee 1.0, `pip install towhee==1.0.0`

**Comment by jaelgu** [comment]
> 

It looks like environment issue. What is your jinja2 version? You may try to downgrade it, for example, 3.1.1.

**Comment by jaelgu** [comment]
Reopen if the issue persists.
