### ISSUE TITLE
Pymilvus: The data fields number is not match with schema.

### ISSUE THREAD

**Issue by wzt-lx** [towhee-io/examples#200]
RuntimeError                              Traceback (most recent call last)
Cell In[33], line 6
      4 next(reader)
      5 for row in reader:
----> 6     insert_pipe(*row)

File D:\anaconda\envs\DL\lib\site-packages\towhee\runtime\runtime_pipeline.py:149, in RuntimePipeline.__call__(self, *inputs)
    147 if self._enable_trace:
    148     self._time_profiler_list.append(graph.time_profiler)
--> 149 return graph(inputs)

File D:\anaconda\envs\DL\lib\site-packages\towhee\runtime\runtime_pipeline.py:104, in _Graph.__call__(self, inputs)
    102 def __call__(self, inputs: Union[Tuple, List]):
    103     f = self.async_call(inputs)
--> 104     return f.result()

File D:\anaconda\envs\DL\lib\site-packages\towhee\runtime\runtime_pipeline.py:34, in _GraphResult.result(self)
     33 def result(self):
---> 34     ret = self._graph.result()
     35     del self._graph
     36     return ret

File D:\anaconda\envs\DL\lib\site-packages\towhee\runtime\runtime_pipeline.py:87, in _Graph.result(self)
     85             errs += node.err_msg + '\n'
     86 if errs:
---> 87     raise RuntimeError(errs)
     88 end_edge_num = self._nodes['_output'].out_edges[0]
     89 res = self._data_queues[end_edge_num]

RuntimeError: Node-ann-insert/milvus-client-2 runs failed, error msg: <DataTypeNotMatchException: (code=0, message=The data fields number is not match with schema.)>, Traceback (most recent call last):
  File "D:\anaconda\envs\DL\lib\site-packages\towhee\runtime\nodes\node.py", line 156, in _call
    return True, self._op(*inputs), None
  File "C:\Users\Administrator\.towhee\operators\ann-insert\milvus-client\versions\main\milvus_client.py", line 45, in __call__
    mr = self._collection.insert(row)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\pymilvus\orm\collection.py", line 535, in insert
    if not self._check_insert_data_schema(data):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\pymilvus\orm\collection.py", line 187, in _check_insert_data_schema
    raise DataTypeNotMatchException(0, ExceptionsMessage.FieldsNumInconsistent)
pymilvus.orm.exceptions.DataTypeNotMatchException: <DataTypeNotMatchException: (code=0, message=The data fields number is not match with schema.)>   pymilvus不支持VARCHAR，然后改成INT64，在导入csv文件时，出现这样的错误

**Comment by shiyu22** [comment]
@wzt-lx Which version of Milvus are you using? Actually Milvus [support varchar datatype](https://milvus.io/docs/create_collection.md#Prepare-Schema) now, please update to the newest version.

**Comment by wzt-lx** [comment]
c5ea2019b632        milvusdb/milvus:v2.0.2                     "/tini -- milvus run…"   5 days ago          Up 2 hours             0.0.0.0:19530->19530/tcp   milvus-standalone
6e594cc20871        quay.io/coreos/etcd:v3.5.0                 "etcd -advertise-cli…"   5 days ago          Up 2 hours             2379-2380/tcp              milvus-etcd
76add99367b6        minio/minio:RELEASE.2020-12-03T00-03-10Z   "/usr/bin/docker-ent…"   5 days ago          Up 2 hours (healthy)   9000/tcp                   milvus-minio
pymilvus                2.0.2

**Comment by wzt-lx** [comment]
def create_milvus_collection(collection_name, dim):
    if utility.has_collection(collection_name):
        utility.drop_collection(collection_name)
    
    fields = [
    FieldSchema(name='id', dtype=DataType.VARCHAR, descrition='ids', max_length=500, is_primary=True, auto_id=False),
    FieldSchema(name='embedding', dtype=DataType.FLOAT_VECTOR, descrition='embedding vectors', dim=dim)
    ]
    schema = CollectionSchema(fields=fields, description='reverse image search')
    collection = Collection(name=collection_name, schema=schema)

    # create IVF_FLAT index for collection.
    index_params = {
        'metric_type':'L2',
        'index_type':"IVF_FLAT",
        'params':{"nlist":2048}
    }
    collection.create_index(field_name="embedding", index_params=index_params)
    return collection

collection = create_milvus_collection('question_answer', 768)


AttributeError                            Traceback (most recent call last)
Cell In[5], line 21
     18     collection.create_index(field_name="embedding", index_params=index_params)
     19     return collection
---> 21 collection = create_milvus_collection('question_answer', 768)

Cell In[5], line 6, in create_milvus_collection(collection_name, dim)
      2 if utility.has_collection(collection_name):
      3     utility.drop_collection(collection_name)
      5 fields = [
----> 6 FieldSchema(name='id', dtype=DataType.VARCHAR, descrition='ids', max_length=500, is_primary=True, auto_id=False),
      7 FieldSchema(name='embedding', dtype=DataType.FLOAT_VECTOR, descrition='embedding vectors', dim=dim)
      8 ]
      9 schema = CollectionSchema(fields=fields, description='reverse image search')
     10 collection = Collection(name=collection_name, schema=schema)

File D:\anaconda\envs\DL\lib\enum.py:429, in EnumMeta.__getattr__(cls, name)
    427     return cls._member_map_[name]
    428 except KeyError:
--> 429     raise AttributeError(name) from None

AttributeError: VARCHAR

**Comment by junjiejiangjjj** [comment]
requires pymilvus >= 2.1
