### ISSUE TITLE
TypeError: can't pickle _thread.lock objects

### ISSUE THREAD

**Issue by zabzd999** [towhee-io/examples#201]
Environment:
- Milvus version: 2.2.8
- Deployment mode(standalone or cluster):standalone 
- MQ type(rocksmq, pulsar or kafka):    no
- SDK version(e.g. pymilvus v2.0.0rc2):2.1.0
- OS(Ubuntu or CentOS): CentOS7.9
- CPU/Memory: 128GB
- GPU: 24GB
- Others:

Current Behavior:
When I run the default example whitch is located in "examples/image/reverse_image_search/1_build_image_search_engine.ipynb", it throws an exception 
https://user-images.githubusercontent.com/6244724/240831658-2a5a480c-932d-4c59-b9be-fb22dfdb82b6.png

how to solve this problem about  the default towhee example ?

**Comment by junjiejiangjjj** [comment]
To update towhee to version 1.0, simply use the following command: "pip install towhee==1.0.0".

**Comment by zabzd999** [comment]
thanks! It works well !
