### ISSUE TITLE
模型使用本地模型吗？

### ISSUE THREAD

**Issue by wfuqiang1982** [towhee-io/examples#204]
image_embedding.timm(model_name='resnet50')在某些环境下无法连接，我想是否能设置加载本地模型如
image_embedding.timm(path='modelpath',model_name='resnet50')

**Comment by junjiejiangjjj** [comment]
https://github.com/huggingface/transformers/issues/10379 Try offline mode

**Comment by jaelgu** [comment]
Close as duplicate of #211
