### ISSUE TITLE
How to reload the trained model weights of resnet50

### ISSUE THREAD

**Issue by wenlovexx** [towhee-io/examples#211]
The following code snippet is an example provided of using the pre-trained ResNet50 model ('resnet50') to generate an image embedding:
`
p = (
    pipe.input('path')
        .map('path', 'img', ops.image_decode())
        .map('img', 'vec', ops.image_embedding.timm(model_name='resnet50'))
        .output('img', 'vec')
)
`

But i want to use trained weights of resnet50(fine-tune) to extract embedding, How to reload the trained model weights of resnet50?
Could you please provide an example.
thanks!

**Comment by wenlovexx** [comment]
I want to use trained weights of resnet50 to extract embedding, How to reload the trained model weights?
Could you please provide an example.
thanks!

**Comment by wenlovexx** [comment]
Hello, could you please take a look at the above question? Thank you

**Comment by jaelgu** [comment]
> Hello, could you please take a look at the above question? Thank you

I've updated the image-embedding/timm operator to allow local checkpoint path. You can clear the towhee cache (normally `~/.towhee/operators/image-embedding/timm`) and try to pass your checkpoint path as below:
```python
ops.image_embedding.timm(model_name='resnet50', checkpoint_path=your_checkpoint_path))
```

**Comment by wenlovexx** [comment]
> > Hello, could you please take a look at the above question? Thank you
> 
> I've updated the image-embedding/timm operator to allow local checkpoint path. You need to clear the towhee cache (normally `~/.towhee/operators/image-embedding/timm`) and then pass your checkpoint path as below:
> 
> ```python
> ops.image_embedding.timm(model_name='resnet50', checkpoint_path=your_checkpoint_path))
> ```
Follow your prompts, I cleared the towhee cache and  add checkpoint path, But the following error occurred
`RuntimeError: Node-image-embedding/timm-1 runs failed, error msg: Create image-embedding/timm-1 operator image-embedding/timm:main with args None and kws {'model_name': 'resnet50', 'checkpoint_path': '', 'device': device(type='cpu')} failed, err: __init__() got an unexpected keyword argument 'checkpoint_path', Traceback (most recent call last):`

**Comment by jaelgu** [comment]
> > > Hello, could you please take a look at the above question? Thank you
> > 
> > 
> > I've updated the image-embedding/timm operator to allow local checkpoint path. You need to clear the towhee cache (normally `~/.towhee/operators/image-embedding/timm`) and then pass your checkpoint path as below:
> > ```python
> > ops.image_embedding.timm(model_name='resnet50', checkpoint_path=your_checkpoint_path))
> > ```
> 
> Follow your prompts, I cleared the towhee cache and add checkpoint path, But the following error occurred(err: **init**() got an unexpected keyword argument 'checkpoint_path'); The version of towhee is 1.0.0, updated the module of towhee but it still doesn't work, could you please help me take a look again.
> 
> `RuntimeError: Node-image-embedding/timm-1 runs failed, error msg: Create image-embedding/timm-1 operator image-embedding/timm:main with args None and kws {'model_name': 'resnet50', 'checkpoint_path': './output_dir/epoch_1/model.pth', 'device': device(type='cpu')} failed, err: __init__() got an unexpected keyword argument 'checkpoint_path'`

Can you try to clear all Towhee cache and then rerun the code?
```bash
rm -rf ~/.towhee
```

**Comment by junjiejiangjjj** [comment]
Using `ops.image_embedding.timm(model_name='resnet50', checkpoint_path='').latest() ` will download the latest op code.

**Comment by wenlovexx** [comment]
I execute `rm -rf ~/.towhee`  rerun the log as follow:

RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_1650/2593314080.py in <module>
      1 # Display embedding result, no need for implementation
----> 2 p_display = p_embed.output('img_path', 'img', 'vec')
      3 DataCollection(p_display(to_insert[1])).show()

~/anaconda3/envs/towhee_env/lib/python3.7/site-packages/towhee/runtime/pipeline.py in output(self, *output_schema)
     99         """
    100         output_schema = self._check_schema(output_schema)
--> 101 
    102         uid = OutputConst.name
    103         dag_dict = deepcopy(self._dag)

~/anaconda3/envs/towhee_env/lib/python3.7/site-packages/towhee/runtime/runtime_pipeline.py in preload(self)
    151     def batch(self, batch_inputs):
    152         graph_res = []
--> 153         for inputs in batch_inputs:
    154             gh = _Graph(self._dag_repr.nodes, self._dag_repr.edges, self._operator_pool, self._thread_pool, self._enable_trace)
    155             if self._enable_trace:

~/anaconda3/envs/towhee_env/lib/python3.7/site-packages/towhee/runtime/runtime_pipeline.py in __init__(self, nodes, edges, operator_pool, thread_pool, time_profiler, trace_edges)
     65         self._input_queue = self._data_queues[0]
     66 
---> 67     def initialize(self):
     68         self._node_runners = []
     69         self._data_queues = dict((name, DataQueue(edge['data'])) for name, edge in self._edges.items())

~/anaconda3/envs/towhee_env/lib/python3.7/site-packages/towhee/runtime/runtime_pipeline.py in _initialize(self)
     81         errs = ''
     82         for node in self._node_runners:
---> 83             if node.status != NodeStatus.FINISHED:
     84                 if node.status ==NodeStatus.FAILED:
     85                     errs += node.err_msg + '\n'

RuntimeError: Node-image-embedding/timm-1 runs failed, error msg: Create image-embedding/timm-1 operator image-embedding/timm:main with args None and kws {'model_name': 'resnet50', 'checkpoint_path': '../fine-tune/resnet/cub_200_output/epoch_12/model.pth', 'device': device(type='cpu')} failed, err: __init__() got an unexpected keyword argument 'checkpoint_path', Traceback (most recent call last):
  File "/root/anaconda3/envs/towhee_env/lib/python3.7/site-packages/towhee/runtime/nodes/node.py", line 94, in initialize
    self._time_profiler.record(self.uid, Event.init_out)
  File "/root/anaconda3/envs/towhee_env/lib/python3.7/site-packages/towhee/runtime/operator_manager/operator_pool.py", line 106, in acquire_op
    Releases the specified operator and all associated resources back to the
  File "/root/anaconda3/envs/towhee_env/lib/python3.7/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 154, in load_operator
    if arg is None:
  File "/root/anaconda3/envs/towhee_env/lib/python3.7/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 137, in _load_operator_from_hub
    be contained within a single directory.
  File "/root/anaconda3/envs/towhee_env/lib/python3.7/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 125, in _load_operator_from_path
    except Exception as e:  # pylint: disable=broad-except
  File "/root/anaconda3/envs/towhee_env/lib/python3.7/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 163, in _instance_operator
  File "/root/.towhee/operators/image-embedding/timm/versions/main/__init__.py", line 19, in timm
    return TimmImage(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'checkpoint_path'
`

**Comment by jaelgu** [comment]
@wenlovexx 
<img width="604" alt="image" src="https://github.com/towhee-io/examples/assets/86251631/9c87941f-d33b-4659-b2e0-7b014faadaa9">

It looks like you're running your code as `root` user and using cache under `/root`. So you should clear towhee cache at `~/.towhee` as root user as well, otherwise `~` presents some other user's home directory. You can check if `~` is the `/root`.

Instead of manually clearing cache, you can try another solution mentioned above: `ops.image_embedding.timm(model_name='resnet50', checkpoint_path='').latest()`

**Comment by wenlovexx** [comment]
`root@iv-ycgso4ma2cebgz695mpi:~# pwd
/root
root@iv-ycgso4ma2cebgz695mpi:~# rm -rf .towhee`

and execude code as 
`ops.image_embedding.timm(model_name='resnet50', checkpoint_path='').latest()`

but the same errer log return

**Comment by jaelgu** [comment]
Close as completed.
