### ISSUE TITLE
TypeError: constr() got an unexpected keyword argument 'regex'

### ISSUE THREAD

**Issue by zhoukewei9700** [towhee-io/examples#214]
I use jupyter notebook to import towhee 1.1.0,but failed
why? How can I solve this?
<img width="415" alt="image" src="https://github.com/towhee-io/examples/assets/77055544/1c0329f0-6912-4af3-aeba-09b825356204">

**Comment by junjiejiangjjj** [comment]
`pydantic` adjust the interface of `constr` https://github.com/pydantic/pydantic/commit/594effa279668bd955e98f1cd5c036b37d3bbd40#diff-f7a381c0918da7ec905bfbe6aff2ccc72c2d0fd6da0dd3011ef1da892e42d57a, please reinstall it:
`pip install pydantic==1.10.10`

**Comment by junjiejiangjjj** [comment]
https://github.com/towhee-io/towhee/pull/2605
