### ISSUE TITLE
save and load model 

### ISSUE THREAD

**Issue by bhuvneshsaini** [towhee-io/examples#217]
How to save and load the model in towhee because sometimes we already have the model and want to use that one?

**Comment by junjiejiangjjj** [comment]
Most towhee operators support passing in local weights.
For example, [timm](https://towhee.io/image-embedding/timm/src/branch/main/timm_image.py) op, you can pass in a local model through the `checkpoint_path` parameter. 
![image](https://github.com/towhee-io/examples/assets/14136703/41256d8f-dda0-4da9-9369-95806c7edf95)

We also provide an interface to train or fine-tune models.
https://towhee.readthedocs.io/en/latest/trainer/trainer.html

**Comment by bhuvneshsaini** [comment]
Hi, I am asking how to save and load the model instead of this "ops.image_embedding.timm(model_name=MODEL, device=DEVICE", as this statement downloads the model.

**Comment by junjiejiangjjj** [comment]
This approach will not download the model, but will instead use the local model. 
```python
ops.image_embedding.timm(model_name='resnet50', device=DEVICE, checkpoint_pah=YOUR_LOCAL_WEIGHTS)
```

or you can create a local operator: https://towhee.readthedocs.io/en/latest/operator/usage.html#custom-operators
