### ISSUE TITLE
ValidationError: 1 validation error for TupleForm while running reverse video search at Evaluation Section

### ISSUE THREAD

**Issue by chandrakalagowda** [towhee-io/examples#218]
I am using
towhee==1.1.1
Pydantic. == 1.10.11

---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[10], line 31
     19         aps.append(sum(precisions) / len(precisions))
     21     return sum(aps) / len(aps)
     23 eval_pipe = (
     24     pipe.input('path')
     25         .flat_map('path', 'path', lambda x: glob.glob(x))
     26         .map('path', 'frames', ops.video_decode.ffmpeg(sample_type='uniform_temporal_subsample', args={'num_samples': 16}))
     27         .map('frames', ('labels', 'scores', 'features'), ops.action_classification.pytorchvideo(model_name='x3d_m', skip_preprocess=True))
     28         .map('features', 'result', ops.ann_search.milvus_client(host='127.0.0.1', port='19530', collection_name='x3d_m', limit=10))  
     29         .map('result', 'predict', lambda x: [i[0] for i in x])
     30         .map('path', 'ground_truth', ground_truth)
---> 31         .window_all(('ground_truth', 'predict'), 'mHR', mean_hit_ratio)
     32         .window_all(('ground_truth', 'predict'), 'mAP', mean_average_precision)
     33         .output('mHR', 'mAP')
     34 )
     36 res = DataCollection(eval_pipe('./test/*/*.mp4'))
     37 res.show()

File ~/Documents/milvus/.milvusenv/lib/python3.11/site-packages/towhee/runtime/pipeline.py:348, in Pipeline.window_all(self, input_schema, output_schema, fn, config)
    326 def window_all(self, input_schema, output_schema, fn, config=None) -> 'Pipeline':
    327     """
    328     Read all rows as single window and perform action.
    329 
   (...)
    346         [10, 14]
    347     """
--> 348     output_schema = self._check_schema(output_schema)
    349     input_schema = self._check_schema(input_schema)
    351     uid = uuid.uuid4().hex

File ~/Documents/milvus/.milvusenv/lib/python3.11/site-packages/towhee/runtime/pipeline.py:517, in Pipeline._check_schema(schema)
    515 @staticmethod
    516 def _check_schema(schema):
--> 517     return TupleForm(schema_data=schema).schema_data

File ~/Documents/milvus/.milvusenv/lib/python3.11/site-packages/pydantic/main.py:341, in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for TupleForm
schema_data -> 0
  string does not match regex "^[a-z][a-z0-9_]*$" (type=value_error.str.regex; pattern=^[a-z][a-z0-9_]*$)

**Comment by shiyu22** [comment]
Hi @chandrakalagowda , it is because the schema in pipeline currently only supports lowercase letters, and the 'mAP' and 'mHR' contains uppercase, so you can switch from uppercase to lowercase and try again :)

Also, I'll submit a PR later to support uppercase as well.

**Comment by chandrakalagowda** [comment]
> Hi @chandrakalagowda , it is because the schema in pipeline currently only supports lowercase letters, and the 'mAP' and 'mHR' contains uppercase, so you can switch from uppercase to lowercase and try again :)
> 
> Also, I'll submit a PR later to support uppercase as well.

Hello Thank you for the quick reply. It works.

<img width="555" alt="image" src="https://github.com/towhee-io/examples/assets/24473622/702226e3-85f6-45a1-8d2f-c29aff58df07">

Is this the line that indicates that? Just for my understanding.

**Comment by shiyu22** [comment]
Yes, you are right. If you are interested, you can also [submit a PR](https://github.com/towhee-io/towhee/pulls) to Towhee, which would be very welcome to a contributor.

BTW, I think you just need to modify this [file](https://github.com/towhee-io/towhee/blob/main/towhee/runtime/check_utils.py#L38).

**Comment by chandrakalagowda** [comment]
@shiyu22 I checked the file.  However, I have lot more questions regarding regex. So please may be now you correct it. Thank you for suggesting it though.

**Comment by shiyu22** [comment]
> @shiyu22 I checked the file. However, I have lot more questions regarding regex. So please may be now you correct it. Thank you for suggesting it though.

Got it, also thanks for you catch this issue.

PR [#2634](https://github.com/towhee-io/towhee/pull/2634) has been submitted, and it will works in the main branch when merged, you can try it with the [source installed towhee](https://docs.towhee.io/Getting%20Started/install/#install-towhee-from-source).
