### ISSUE TITLE
code needs to be modified

### ISSUE THREAD

**Issue by kennymingtu** [towhee-io/examples#219]
import cv2
from towhee.types.image import Image

def read_images(img_paths):
    imgs = []
    for p in img_paths:
        imgs.append(Image(cv2.imread(p), 'BGR'))
    return imgs

p_search_img = (
    p_search_pre.map('pred', 'pred images', read_images)
                .output('img', 'pred images')
)
DataCollection(p_search_img('test/goldfish/*.JPEG')).show()

needs to be updated from pred images to pred_images

**Comment by junjiejiangjjj** [comment]
@shiyu22

**Comment by shiyu22** [comment]
> import cv2 from towhee.types.image import Image
> 
> def read_images(img_paths): imgs = [] for p in img_paths: imgs.append(Image(cv2.imread(p), 'BGR')) return imgs
> 
> p_search_img = ( p_search_pre.map('pred', 'pred images', read_images) .output('img', 'pred images') ) DataCollection(p_search_img('test/goldfish/*.JPEG')).show()
> 
> needs to be updated from pred images to pred_images

@kennymingtu Thanks for your issue, I think you are right. And can you submit a PR to modify it?
