### ISSUE TITLE
Model not loading in 1_build_question_answering_engine.ipynb

### ISSUE THREAD

**Issue by jessiefroy** [towhee-io/examples#223]
I am trying to replicate/run this (under 1_build_question_answering_engine.ipynb cell 5):

```
insert_pipe = (
    pipe.input('id', 'question', 'answer')
        .map('question', 'vec', ops.text_embedding.dpr(model_name='facebook/dpr-ctx_encoder-single-nq-base'))
        .map('vec', 'vec', lambda x: x / np.linalg.norm(x, axis=0))
        .map(('id', 'vec'), 'insert_status', ops.ann_insert.milvus_client(host='127.0.0.1', port='19530', collection_name='question_answer'))
        .output()
)
```

But i keep getting the following error: 2

023-08-02 01:38:37,706 - 8171578624 - connectionpool.py-connectionpool:546 - DEBUG: [https://huggingface.co:443](https://huggingface.co/) "HEAD /facebook/dpr-ctx_encoder-single-nq-base/resolve/main/tokenizer_config.json HTTP/1.1" 200 0
2023-08-02 01:38:37,747 - 8171578624 - dpr.py-dpr:39 - ERROR: Fail to load model by name: facebook/dpr-ctx_encoder-single-nq-base
2023-08-02 01:38:37,749 - 8171578624 - node.py-node:142 - INFO: text-embedding/dpr-0 ends with status: NodeStatus.FAILED
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[124], line 6
      1 insert_pipe = (
      2     pipe.input('id', 'question', 'answer')
      3         .map('question', 'vec', ops.text_embedding.dpr(model_name='facebook/dpr-ctx_encoder-single-nq-base'))
      4         .map('vec', 'vec', lambda x: x / np.linalg.norm(x, axis=0))
      5         .map(('id', 'vec'), 'insert_status', ops.ann_insert.milvus_client(host='127.0.0.1', port='19530', collection_name='question_answer'))
----> 6         .output()
      7 )

File /opt/homebrew/lib/python3.11/site-packages/towhee/runtime/pipeline.py:101, in Pipeline.output(self, *output_schema)
     98 dag_dict[self._clo_node]['next_nodes'].append(uid)
    100 run_pipe = RuntimePipeline(dag_dict)
--> 101 run_pipe.preload()
    102 return run_pipe

File /opt/homebrew/lib/python3.11/site-packages/towhee/runtime/runtime_pipeline.py:153, in RuntimePipeline.preload(self)
    149 def preload(self):
    150     """
    151     Preload the operators.
    152     """
--> 153     return _Graph(self._dag_repr.nodes, self._dag_repr.edges, self._operator_pool, self._thread_pool, TimeProfiler(False))

File /opt/homebrew/lib/python3.11/site-packages/towhee/runtime/runtime_pipeline.py:67, in _Graph.__init__(self, nodes, edges, operator_pool, thread_pool, time_profiler, trace_edges)
     65 self.features = None
     66 self._time_profiler.record(Event.pipe_name, Event.pipe_in)
---> 67 self._initialize()
     68 self._input_queue = self._data_queues[0]

File /opt/homebrew/lib/python3.11/site-packages/towhee/runtime/runtime_pipeline.py:83, in _Graph._initialize(self)
     81 node = create_node(self._nodes[name], self._operator_pool, in_queues, out_queues, self._time_profiler)
     82 if not node.initialize():
---> 83     raise RuntimeError(node.err_msg)
     84 self._node_runners.append(node)

RuntimeError: Node-text-embedding/dpr-0 runs failed, error msg: Create text-embedding/dpr-0 operator text-embedding/dpr:main with args None and kws {'model_name': 'facebook/dpr-ctx_encoder-single-nq-base'} failed, err: 
DPRContextEncoder requires the PyTorch library but it was not found in your environment. Checkout the instructions on the
installation page: https://pytorch.org/get-started/locally/ and follow the ones that match your environment.
Please note that you may need to restart your runtime after installation.
, Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/towhee/runtime/nodes/node.py", line 88, in initialize
    self._op = self._op_pool.acquire_op(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/towhee/runtime/operator_manager/operator_pool.py", line 106, in acquire_op
    op = self._op_loader.load_operator(hub_op_id, op_args, op_kws, tag, latest)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 154, in load_operator
    op = factory(function, arg, kws, tag, latest)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 137, in _load_operator_from_hub
    return self._load_operator_from_path(path, function, arg, kws, tag)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 125, in _load_operator_from_path
    return self._instance_operator(op, arg, kws) if op is not None else None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 163, in _instance_operator
    return op(*arg, **kws) if kws is not None else op(*arg)
           ^^^^^^^^^^^^^^^
  File "/Users/jess/.towhee/operators/text-embedding/dpr/versions/main/__init__.py", line 19, in dpr
    return Dpr(**kwargs)
           ^^^^^^^^^^^^^
  File "/Users/jess/.towhee/operators/text-embedding/dpr/versions/main/dpr.py", line 40, in __init__
    raise e
  File "/Users/jess/.towhee/operators/text-embedding/dpr/versions/main/dpr.py", line 37, in __init__
    self.model = DPRContextEncoder.from_pretrained(model_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1039, in __getattribute__
    requires_backends(cls, cls._backends)
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1027, in requires_backends
    raise ImportError("".join(failed))
ImportError: 
DPRContextEncoder requires the PyTorch library but it was not found in your environment. Checkout the instructions on the
installation page: https://pytorch.org/get-started/locally/ and follow the ones that match your environment.
Please note that you may need to restart your runtime after installation.

**Comment by jaelgu** [comment]
The transformers package requires pytorch in your environment. I've just added to the requirements of the operator: https://towhee.io/text-embedding/dpr/src/branch/main/requirements.txt

So you can either run with latest operator: `ops.text_embedding.dpr(model_name='facebook/dpr-ctx_encoder-single-nq-base').latest()` (this will try to automatically install torch),
Or manually install pytorch following instructions at https://pytorch.org/get-started/locally/ and then re-run the same code.

**Comment by jessiefroy** [comment]
Thanks for the reply,

I tried doing both (install all the requirements including torch and torch vision) but I still get this error:
AttributeError                            Traceback (most recent call last)
Cell In[165], line 3      1 insert_pipe = (
     2     pipe.input('id', 'question', 'answer')----> 3         .map('question', 'vec', ops.text_embedding.dpr(model_name='facebook/dpr-ctx_encoder-single-nq-base')).latest()
     4         .map('vec', 'vec', lambda x: x / np.linalg.norm(x, axis=0))
     5         .map(('id', 'vec'), 'insert_status', ops.ann_insert.milvus_client(host='127.0.0.1', port='19530', collection_name='question_answer'))
     6         .output()
     7 )

AttributeError: 'Pipeline' object has no attribute 'latest'


Regards,
Jess.

**Comment by jessiefroy** [comment]
This is what I get without the latest() attribute added.


Regards,
Jess.

**Comment by jessiefroy** [comment]
Please ignore, I didn’t realize its already working.  Thanks for your help.

Regards,
Jess.
