### ISSUE TITLE
Loading Local Models and Downloading Online Models

### ISSUE THREAD

**Issue by tian-003** [towhee-io/examples#225]
Hello. When I use ''ops.image_embedding.timm(model_name='resnet50', checkpoint_path=my_checkpoint_path)'' , even if I specify the ''checkpoint_path='' to a specific model path, it still checks if the pre-trained model exists in the [ .cache] directory. If it is not present, the function automatically downloads the pre-trained model. In this case, is it actually using the model I specified in 'checkpoint_path=' ? Thanks for  you!

**Comment by jaelgu** [comment]
Fixed by latest [timm operator](https://towhee.io/image-embedding/timm).
Use the code below to force re-download the latest operator: `ops.image_embedding.timm(xxx).latest()`

**Comment by tian-003** [comment]
Thank you! The problem has been solved! Good!
