### ISSUE TITLE
please explain what entity does the "results" refer to in the code snippet

### ISSUE THREAD

**Issue by chandrakalagowda** [towhee-io/examples#226]
import cv2
from towhee.types.image import Image

id_img = df.set_index('id')['path'].to_dict()

def read_images(results):
    imgs = []
    for re in results:
        path = id_img[re.id]
        imgs.append(Image(cv2.imread(path), 'BGR'))
    return imgs
________________

I do not understand what does the results in the line def read_images(results): refer to. 

why is it called results?

What does 

for re in results --- loop over?

(I understand it. some how loops over all id's in the dictionary. But unable to understand how this code is doing it)

**Comment by jaelgu** [comment]
> import cv2 from towhee.types.image import Image
> 
> id_img = df.set_index('id')['path'].to_dict()
> 
> def read_images(results): imgs = [] for re in results: path = id_img[re.id] imgs.append(Image(cv2.imread(path), 'BGR')) return imgs
> 
> I do not understand what does the results in the line def read_images(results): refer to.
> 
> why is it called results?
> 
> What does
> 
> for re in results --- loop over?
> 
> (I understand it. some how loops over all id's in the dictionary. But unable to understand how this code is doing it)

The `read_images` function is prepared for reading images from [Milvus search results](https://milvus.io/api-reference/pymilvus/v2.2.x/SearchResult/SearchResult().md).

**Comment by chandrakalagowda** [comment]
@jaelgu Thank. you.  That was not confusion. I Will try to work on it a bit more.  Thanks for replying though
