### ISSUE TITLE
TypeError: 'PretrainedCfg' object is not subscriptable

### ISSUE THREAD

**Issue by riichg5** [towhee-io/examples#227]
`

from towhee import AutoPipes, AutoConfig
import glob

emb_conf = AutoConfig.load_config('video_embedding')
emb_conf.collection = 'video_copy_detection'
emb_conf.leveldb_path = 'url_vec.db'
emb_conf.hbase_table = 'video_copy_detection'
emb_conf.device = 0
emb_conf.milvus_host = 'xx.xx.xx.xx'
print(emb_conf)
emb_pipe = AutoPipes.pipeline('video_embedding', emb_conf)

path = glob.glob('VCSL-demo-en/*/*')

for i in path:
    result = emb_pipe(i)

del emb_pipe

`

**error:**

---------------------------------------------------------------------------

> 
> RuntimeError                              Traceback (most recent call last)
> Cell In[4], line 11
>       9 emb_conf.milvus_host = 'xxxx.xx.xxx'
>      10 print(emb_conf)
> ---> 11 emb_pipe = AutoPipes.pipeline('video_embedding', emb_conf)
>      13 path = glob.glob('VCSL-demo-en/*/*')
>      15 for i in path:
> 
> File ~/video_compare/venv/lib/python3.10/site-packages/towhee/runtime/auto_pipes.py:78, in AutoPipes.pipeline(name, *args, **kwargs)
>      76 with AutoPipes._lock:
>      77     if name in AutoPipes._PIPES_DEF:
> ---> 78         return AutoPipes._PIPES_DEF[name](*args, **kwargs)
>      80     with set_pipe_name(name):
>      81         pipe_loader.PipelineLoader.load_pipeline(name)
> 
> File ~/video_compare/venv/lib/python3.10/site-packages/towhee/runtime/auto_pipes.py:68, in AutoPipes.register.<locals>.wrapper(*args, **kwargs)
>      66 @wraps(pipe_def)
>      67 def wrapper(*args, **kwargs):
> ---> 68     return pipe_def(*args, **kwargs)
> 
> File ~/video_compare/venv/lib/python3.10/site-packages/towhee/pipelines/video_embedding.py:145, in video_embedding(config)
>     142     kv_op = ops.kvstorage.insert_leveldb(path=config.leveldb_path)
>     143 norm_op = None if config.model == 'isc' else ops.towhee.np_normalize()
> --> 145 return _video_embedding(decode_op, emb_op, milvus_op, kv_op, norm_op, allow_triton, config.device)
> 
> File ~/video_compare/venv/lib/python3.10/site-packages/towhee/pipelines/video_embedding.py:89, in _video_embedding(decode_op, emb_op, milvus_op, kv_op, norm_op, allow_triton, device)
>      87 if norm_op:
>      88     return _norm()
> ---> 89 return _unnorm()
> 
> File ~/video_compare/venv/lib/python3.10/site-packages/towhee/pipelines/video_embedding.py:84, in _video_embedding.<locals>._unnorm()
>      76 def _unnorm():
>      77     return (
>      78         pipe.input('url')
>      79             .flat_map('url', 'frames', decode_op)
>      80             .map('frames', 'emb', emb_op, config=op_config)
>      81             .map(('url', 'emb'), 'milvus_res', milvus_op)
>      82             .window_all('emb', 'video_emb', merge_ndarray)
>      83             .map(('url', 'video_emb'), ('insert_status'), kv_op)
> ---> 84             .output()
>      85     )
> 
> File ~/video_compare/venv/lib/python3.10/site-packages/towhee/runtime/pipeline.py:101, in Pipeline.output(self, *output_schema)
>      98 dag_dict[self._clo_node]['next_nodes'].append(uid)
>     100 run_pipe = RuntimePipeline(dag_dict)
> --> 101 run_pipe.preload()
>     102 return run_pipe
> 
> File ~/video_compare/venv/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py:153, in RuntimePipeline.preload(self)
>     149 def preload(self):
>     150     """
>     151     Preload the operators.
>     152     """
> --> 153     return _Graph(self._dag_repr.nodes, self._dag_repr.edges, self._operator_pool, self._thread_pool, TimeProfiler(False))
> 
> File ~/video_compare/venv/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py:67, in _Graph.__init__(self, nodes, edges, operator_pool, thread_pool, time_profiler, trace_edges)
>      65 self.features = None
>      66 self._time_profiler.record(Event.pipe_name, Event.pipe_in)
> ---> 67 self._initialize()
>      68 self._input_queue = self._data_queues[0]
> 
> File ~/video_compare/venv/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py:83, in _Graph._initialize(self)
>      81 node = create_node(self._nodes[name], self._operator_pool, in_queues, out_queues, self._time_profiler)
>      82 if not node.initialize():
> ---> 83     raise RuntimeError(node.err_msg)
>      84 self._node_runners.append(node)
> 
> RuntimeError: Node-image-embedding/isc-1 runs failed, error msg: Create image-embedding/isc-1 operator image-embedding/isc:main with args None and kws {'img_size': 512, 'device': 0} failed, err: 'PretrainedCfg' object is not subscriptable, Traceback (most recent call last):
>   File "/home/libo/video_compare/venv/lib/python3.10/site-packages/towhee/runtime/nodes/node.py", line 88, in initialize
>     self._op = self._op_pool.acquire_op(
>   File "/home/libo/video_compare/venv/lib/python3.10/site-packages/towhee/runtime/operator_manager/operator_pool.py", line 106, in acquire_op
>     op = self._op_loader.load_operator(hub_op_id, op_args, op_kws, tag, latest)
>   File "/home/libo/video_compare/venv/lib/python3.10/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 154, in load_operator
>     op = factory(function, arg, kws, tag, latest)
>   File "/home/libo/video_compare/venv/lib/python3.10/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 137, in _load_operator_from_hub
>     return self._load_operator_from_path(path, function, arg, kws, tag)
>   File "/home/libo/video_compare/venv/lib/python3.10/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 125, in _load_operator_from_path
>     return self._instance_operator(op, arg, kws) if op is not None else None
>   File "/home/libo/video_compare/venv/lib/python3.10/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 163, in _instance_operator
>     return op(*arg, **kws) if kws is not None else op(*arg)
>   File "/home/libo/.towhee/operators/image-embedding/isc/versions/main/__init__.py", line 19, in isc
>     return Isc(**kwargs)
>   File "/home/libo/.towhee/operators/image-embedding/isc/versions/main/isc.py", line 96, in __init__
>     interpolation=self.config['interpolation'],
> TypeError: 'PretrainedCfg' object is not subscriptable
> 

**env:**

towhee                    1.1.0
towhee.models             1.1.0

**Comment by zc277584121** [comment]
what is your timm version? @riichg5

**Comment by riichg5** [comment]
> 

(venv) (base) test:~/video_compare$ pip list | grep timm
timm                      0.9.5

**Comment by zc277584121** [comment]
fix by https://towhee.io/image-embedding/isc/commit/6dedf86de083b1f01d8bca071a825a252294b30d
please update your isc operator and re-run your script
@riichg5

**Comment by riichg5** [comment]
Switched to timm==0.6.13, the problem is solved, thank you.

**Comment by zc277584121** [comment]
@riichg5 
Glad you solved the problem. I updated the code of the isc operator, you can also update the latest isc operator, which can also solve your problem.

**Comment by riichg5** [comment]
@zc277584121  thank you much, now use timm==0.9.5 also works well!
