### ISSUE TITLE
RuntimeError: Node-video-copy-detection/temporal-network-7 runs failed, error msg: module 'numpy' has no attribute 'bool'.

### ISSUE THREAD

**Issue by riichg5** [towhee-io/examples#228]
![image](https://github.com/towhee-io/examples/assets/4560963/432b070f-5fef-4473-9790-2795140bd38d)

`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File <timed exec>:34

File ~/video_compare/venv/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py:159, in RuntimePipeline.__call__(self, *inputs)
    155 def __call__(self, *inputs):
    156     """
    157     Output with ordering matching the input `DataQueue`.
    158     """
--> 159     return self._call(*inputs, profiler=False, tracer=False)[0]

File ~/video_compare/venv/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py:177, in RuntimePipeline._call(self, profiler, tracer, trace_edges, *inputs)
    174 time_profiler = TimeProfiler(True) if profiler else TimeProfiler(False)
    175 graph = _Graph(self._dag_repr.nodes, self._dag_repr.edges, self._operator_pool, self._thread_pool, time_profiler, trace_edges)
--> 177 return graph(inputs), [graph.time_profiler] if profiler else None, [graph.data_queues] if tracer else None

File ~/video_compare/venv/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py:116, in _Graph.__call__(self, inputs)
    114 def __call__(self, inputs: Union[Tuple, List]):
    115     f = self.async_call(inputs)
--> 116     return f.result()

File ~/video_compare/venv/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py:34, in _GraphResult.result(self)
     33 def result(self):
---> 34     ret = self._graph.result()
     35     self._graph.release_op()
     36     del self._graph

File ~/video_compare/venv/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py:95, in _Graph.result(self)
     93             errs += node.err_msg + '\n'
     94 if errs:
---> 95     raise RuntimeError(errs)
     96 end_edge_num = self._nodes['_output'].out_edges[0]
     97 res = self._data_queues[end_edge_num]

RuntimeError: Node-video-copy-detection/temporal-network-7 runs failed, error msg: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations, Traceback (most recent call last):
  File "/home/libo/video_compare/venv/lib/python3.10/site-packages/towhee/runtime/nodes/node.py", line 158, in _call
    return True, self._op(*inputs), None
  File "/home/libo/.towhee/operators/video-copy-detection/temporal-network/versions/main/tn.py", line 204, in __call__
    ranges, scores = tn(sim_map, self._tn_max_step, self._tn_top_k, self._max_path, self._min_sim, self._min_length, self._max_iou)
  File "/home/libo/.towhee/operators/video-copy-detection/temporal-network/versions/main/tn.py", line 113, in tn
    C3 = np.ones(C2.shape, dtype=np.bool)
  File "/home/libo/video_compare/venv/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
, Traceback (most recent call last):
  File "/home/libo/video_compare/venv/lib/python3.10/site-packages/towhee/runtime/nodes/node.py", line 171, in process
    self.process_step()
  File "/home/libo/video_compare/venv/lib/python3.10/site-packages/towhee/runtime/nodes/_map.py", line 63, in process_step
    assert succ, msg
AssertionError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations, Traceback (most recent call last):
  File "/home/libo/video_compare/venv/lib/python3.10/site-packages/towhee/runtime/nodes/node.py", line 158, in _call
    return True, self._op(*inputs), None
  File "/home/libo/.towhee/operators/video-copy-detection/temporal-network/versions/main/tn.py", line 204, in __call__
    ranges, scores = tn(sim_map, self._tn_max_step, self._tn_top_k, self._max_path, self._min_sim, self._min_length, self._max_iou)
  File "/home/libo/.towhee/operators/video-copy-detection/temporal-network/versions/main/tn.py", line 113, in tn
    C3 = np.ones(C2.shape, dtype=np.bool)
  File "/home/libo/video_compare/venv/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
`

**ENV**

numpy                     1.24.4
towhee                    1.1.1
towhee.models             1.1.1

**Comment by riichg5** [comment]
@zc277584121  need your help!

**Comment by wxywb** [comment]
I have updated the operator, you need to delete your downloaded operator then retry.

**Comment by riichg5** [comment]
@wxywb  solved, thks!
