### ISSUE TITLE
TypeError: 'torch._C.Node' object is not subscriptable

### ISSUE THREAD

**Issue by PG-9-9** [towhee-io/examples#241]
Hey Everyone I am experimenting with actionclip , and while running my config model, its showing a following error, I assume this has to be the package fix, but maybe I am wrong, Any help would be much apperciated:

> TypeError: 'torch._C.Node' object is not subscriptable

Config file:
`from towhee import ops, pipe, DataCollection
from glob import glob

p = (
    pipe.input('path')
    .map('path', 'frames', ops.video_decode.ffmpeg())
    .map('frames', ('labels', 'scores', 'features'), ops.action_classification.actionclip(model_name='clip_vit_b16'))
    .output('path', 'labels', 'scores', 'features')
)

DataCollection(p('../sources/reverse_video_search/train/tap_dancing/*.mp4')).show()
`

**Comment by junjiejiangjjj** [comment]
You can refer to https://github.com/openai/CLIP/issues/79

**Comment by PG-9-9** [comment]
Thanks, @junjiejiangjjj. Based on the issue reference you provided, I'd like to share the fix that worked for me. For PyTorch versions greater than **2.0.0**, the signature **jit=False** needs to be set. However, in the code sample provided above, there's no direct call to clip.py where one can add this signature. A workaround is to set the **jit=false** directly within clip.py found under **towhee/models/clip**. I explicitly made this assignment at **line 690.**

**Comment by PG-9-9** [comment]
Thanks, @junjiejiangjjj. Based on the issue reference you provided, I'd like to share the fix that worked for me. For PyTorch versions greater than 2.0.0, the signature **jit=False** needs to be set. However, in the code sample provided above, there's no direct call to clip.py where one can add this signature. A workaround is to set the jit value to false directly within **clip.py** found under **towhee/models/clip**. I explicitly made this assignment at **line 690.**
