### ISSUE TITLE
 Build a Milvus Powered Image Search Engine in Minutes Lack of dependency on installed parts

### ISSUE THREAD

**Issue by jingkl** [towhee-io/examples#50]
It should also be clear that the following dependencies need to be installed

1. <img width="837" alt="截屏2022-06-08 10 31 58" src="https://user-images.githubusercontent.com/34296482/172552879-3b55514b-ef2d-4ff6-8963-686b45377370.png">
2. <img width="696" alt="截屏2022-06-08 10 40 51" src="https://user-images.githubusercontent.com/34296482/172552899-4d60a009-383d-4a7e-b3b7-cf6fa1d76b85.png">
3. <img width="982" alt="截屏2022-06-08 10 54 48" src="https://user-images.githubusercontent.com/34296482/172552917-8594bce8-b3fd-4825-8a00-de597a0badd3.png">

**Comment by shiyu22** [comment]
Actually those dependencies will automatically install with towhee's timm operator, maybe something wrong when towhee install the packages. Can you remove **~/.towhee/hub/image-embedding/timm/main** and rerun it?

**Comment by jingkl** [comment]
Verified, close issue
