### ISSUE TITLE
Visualize Nearest Neighbor Search on Image Search lack faiss package

### ISSUE THREAD

**Issue by jingkl** [towhee-io/examples#54]
<img width="1122" alt="截屏2022-06-08 18 38 42" src="https://user-images.githubusercontent.com/34296482/172596860-029f8bae-0e8e-48a2-8e37-b1d99a88e316.png">

**Comment by shiyu22** [comment]
You can [install Faiss](https://github.com/facebookresearch/faiss/blob/main/INSTALL.md) with conda, and a PR will fix it.

**Comment by jingkl** [comment]
Verified, close issue
