### ISSUE TITLE
Build a Milvus Powered Text-Image Search Engine in Minutes run raise an error

### ISSUE THREAD

**Issue by jingkl** [towhee-io/examples#55]
<img width="1081" alt="截屏2022-06-08 18 50 20" src="https://user-images.githubusercontent.com/34296482/172598904-7338c979-e134-4656-9546-ee9e5539926c.png">
<img width="1097" alt="截屏2022-06-08 18 50 05" src="https://user-images.githubusercontent.com/34296482/172598930-2bfa749b-1b08-4afa-969c-3c97b189d8cc.png">

**Comment by jingkl** [comment]
Deep Dive into Text-Image Search Engine with Towhee have same error
<img width="1107" alt="截屏2022-06-08 18 52 55" src="https://user-images.githubusercontent.com/34296482/172599345-185e56af-c51a-407f-b50d-5f1f232c6075.png">
<img width="1069" alt="截屏2022-06-08 18 52 44" src="https://user-images.githubusercontent.com/34296482/172599314-7f6f412f-0085-4a7a-adf3-b2c32b2fe24f.png">

**Comment by shiyu22** [comment]
I think we need to add `python -m pip install -q towhee.models` in the Preparation, @dreamfireyu can you take a look?

**Comment by wxywb** [comment]
@shiyu22 , I think all operators in hub depends on modules in towhee.models will also incur this problem, so we needs a general solution.

**Comment by jaelgu** [comment]
Most notebooks should use latest code of towhee since most `towhee.models` are added after 0.6.1

**Comment by jingkl** [comment]
Verified, close issue
