### ISSUE TITLE
[Bug]:The dataset is extracted from a file that is not in csv format

### ISSUE THREAD

**Issue by jingkl** [towhee-io/examples#60]
<img width="1080" alt="截屏2022-06-09 16 06 17" src="https://user-images.githubusercontent.com/34296482/172813443-957066d9-ce6e-4ba5-83a5-da8a4d11679a.png">
<img width="1154" alt="截屏2022-06-09 16 18 22" src="https://user-images.githubusercontent.com/34296482/172813471-f4dc7361-89bb-42cd-98de-436895cb5466.png">

**Comment by jaelgu** [comment]
@jingkl Fixed. Please check and then close this issue.
