### ISSUE TITLE
[Bug]How to Build a Text-Video Retrieval Engine lack of package

### ISSUE THREAD

**Issue by jingkl** [towhee-io/examples#61]
<img width="1091" alt="截屏2022-06-09 16 12 51" src="https://user-images.githubusercontent.com/34296482/172813663-0c03cf75-ed40-4291-bf86-958631179c55.png">

**Comment by shiyu22** [comment]
PR #64 has fixed it, @jingkl can you try again?

**Comment by jingkl** [comment]
Verified Close issue
