### ISSUE TITLE
Deep Dive Reverse Video Search raise an error

### ISSUE THREAD

**Issue by jingkl** [towhee-io/examples#69]
```
import time
import towhee


# Please note the first time run will take time to download model and other files.

start = time.time()

collection = create_milvus_collection('x3d_m', 2048)

dc = (
    towhee.read_csv('reverse_video_search.csv')
      .runas_op['id', 'id'](func=lambda x: int(x))
      .video_decode.ffmpeg['path', 'frames'](sample_type='uniform_temporal_subsample', args={'num_samples': 16})
      .action_classification['frames', ('labels', 'scores', 'features')].pytorchvideo(
          model_name='x3d_m', skip_preprocess=True)
      .to_milvus['id', 'features'](collection=collection, batch=10)
)

end = time.time()

print('Total insert time: %.2fs'%(end-start))
print('Total number of inserted data is {}.'.format(collection.num_entities))
```
<img width="1103" alt="截屏2022-06-13 22 41 53" src="https://user-images.githubusercontent.com/34296482/173380564-347c7299-9818-43db-8c6f-d83bdd4a762e.png">

**Comment by jingkl** [comment]
```
import towhee
import time


# Please note the first time run will take time to download model and other files.

start = time.time()

collection = create_milvus_collection('timesformer', 768)

dc = (
    towhee.read_csv('reverse_video_search.csv')
      .runas_op['id', 'id'](func=lambda x: int(x))
      .video_decode.ffmpeg['path', 'frames'](sample_type='uniform_temporal_subsample', args={'num_samples': 8})
      .action_classification['frames', ('labels', 'scores', 'vec')].timesformer(skip_preprocess=True)
      .tensor_normalize['vec', 'vec']()
      .to_milvus['id', 'vec'](collection=collection, batch=10)
)

end = time.time()

print('Total insert time: %.2fs'%(end-start))
print('Total number of inserted data is {}.'.format(collection.num_entities))

start = time.time()

benchmark = (
    towhee.glob['path']('./test/*/*.mp4')
        .video_decode.ffmpeg['path', 'frames'](sample_type='uniform_temporal_subsample', args={'num_samples': 8})
        .action_classification['frames', ('labels', 'scores', 'vec')].timesformer(skip_preprocess=True)
        .tensor_normalize['vec', 'vec']()
        .milvus_search['vec', 'result'](collection=collection, limit=10)
        .runas_op['path', 'ground_truth'](func=ground_truth)
        .runas_op['result', 'result'](func=lambda res: [x.id for x in res])
        .with_metrics(['mean_hit_ratio', 'mean_average_precision'])
        .evaluate['ground_truth', 'result']('timesformer')
        .report()
)

end = time.time()

print('Total search time: %.2fs'%(end-start))
```
<img width="925" alt="截屏2022-06-13 22 48 13" src="https://user-images.githubusercontent.com/34296482/173380956-023e1c49-8e5a-4df8-b4c1-7d3240d2b1ca.png">

**Comment by jaelgu** [comment]
> ```
> import towhee
> import time
> 
> 
> # Please note the first time run will take time to download model and other files.
> 
> start = time.time()
> 
> collection = create_milvus_collection('timesformer', 768)
> 
> dc = (
>     towhee.read_csv('reverse_video_search.csv')
>       .runas_op['id', 'id'](func=lambda x: int(x))
>       .video_decode.ffmpeg['path', 'frames'](sample_type='uniform_temporal_subsample', args={'num_samples': 8})
>       .action_classification['frames', ('labels', 'scores', 'vec')].timesformer(skip_preprocess=True)
>       .tensor_normalize['vec', 'vec']()
>       .to_milvus['id', 'vec'](collection=collection, batch=10)
> )
> 
> end = time.time()
> 
> print('Total insert time: %.2fs'%(end-start))
> print('Total number of inserted data is {}.'.format(collection.num_entities))
> 
> start = time.time()
> 
> benchmark = (
>     towhee.glob['path']('./test/*/*.mp4')
>         .video_decode.ffmpeg['path', 'frames'](sample_type='uniform_temporal_subsample', args={'num_samples': 8})
>         .action_classification['frames', ('labels', 'scores', 'vec')].timesformer(skip_preprocess=True)
>         .tensor_normalize['vec', 'vec']()
>         .milvus_search['vec', 'result'](collection=collection, limit=10)
>         .runas_op['path', 'ground_truth'](func=ground_truth)
>         .runas_op['result', 'result'](func=lambda res: [x.id for x in res])
>         .with_metrics(['mean_hit_ratio', 'mean_average_precision'])
>         .evaluate['ground_truth', 'result']('timesformer')
>         .report()
> )
> 
> end = time.time()
> 
> print('Total search time: %.2fs'%(end-start))
> ```
> 
> <img alt="截屏2022-06-13 22 48 13" width="925" src="https://user-images.githubusercontent.com/34296482/173380956-023e1c49-8e5a-4df8-b4c1-7d3240d2b1ca.png">

You need to install the correct towhee version, which at least include https://github.com/towhee-io/towhee/blob/main/towhee/types/video_frame.py (commit 7e8be9ad2)

**Comment by jingkl** [comment]
Verified, close issue
