### ISSUE TITLE
[Bug] Build a Video Classification System in 5 Lines raise an error"IndexError: list index out of range"

### ISSUE THREAD

**Issue by jingkl** [towhee-io/examples#71]
```
import towhee

(
    towhee.glob['path']('./train/tap_dancing/*.mp4').unstream()
          .video_decode.ffmpeg['path', 'frames'](sample_type='uniform_temporal_subsample', args={'num_samples': 16})
          .action_classification['frames', ('predicts', 'scores', 'features')].pytorchvideo(
              model_name='x3d_m', skip_preprocess=True, topk=5)
          .select['path', 'predicts', 'scores']()
          .show()
)
```

<img width="1046" alt="截屏2022-06-16 11 39 57" src="https://user-images.githubusercontent.com/34296482/173986694-18093a0e-2ebf-4421-b42b-e87d2268eb75.png">

towhee version
```
towhee-0.7.0-py3-none-any.whl
towhee.models-0.7.0-py3-none-any.whl
```
The above error was reported even though the relevant cache had been cleared locally
```
rm -rf ~/.cache/torch/hub/checkpoints/
 rm -rf ~/.towhee/
```

**Comment by jaelgu** [comment]
Can't reproduce the issue with `towhee-0.7.0-py3-none-any.whl` & `towhee.models-0.7.0-py3-none-any.whl`.
@jingkl Please check your torch version. What's your os?

**Comment by jingkl** [comment]
verification it，close issue
