### ISSUE TITLE
期待以文搜图应用示例可以支持中文

### ISSUE THREAD

**Issue by klisly** [towhee-io/examples#96]
通过中文文本搜索图片这个想法已经在我的想法清单中列了好久。
很苦恼的地方在于，自己手动训练模型的话，需要投入很多时间，做了很多调研，最终没有花时间去做。
很开心，看到towhee提供以文搜图的应用示例。
比较遗憾的是，目前只支持英文，期待能支持中文搜索图片

**Comment by shiyu22** [comment]
@klisly That's a good idea, and it's the same as [#1518](https://github.com/towhee-io/towhee/issues/1518).
